feat: add statement api.
payjp/payjp-php pull request #39
Opened 2023-09-27 06:24 UTC by nonz250

## Description

Add statement api.

* Statement
* StatementDownloadUrl

2023-09-27 11:07 UTC, darai0512 approved these changes
自分がやる場合も同じ実装になると思います、テストもモックでありがたい。

あとはdocsapiにサンプル書く。

2023-09-27 11:39 UTC, darai0512 requested changes
エンドポイントに合わせて`s/StatementDownloadUrl/StatementUrl/g`にしたいです。

またTenantTransferからStatementUrlもが生えると思うので、Statementのコンストラクタと似たものをTenantTransferに生やすと良いかと。

2023-09-28 08:04 UTC, nonz250 commented
@darai0512 

* TenantTransfer に StatementUrl 追加。
* Statement の Download url を作成するエンドポイントの仕様変更を反映。

以上対応してます。

2023-09-29 07:51 UTC, darai0512 approved these changes

2023-09-29 07:51 UTC, merged